import Head from "next/head";
import { api } from "~/utils/api";
import { LoadingSpinner } from "~/components/loading";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import { SideBar } from "~/components/sidebar";
import { MobileHeader } from "~/components/mobileheader";
import { createServerSideHelpers } from '@trpc/react-query/server';
import superjson from 'superjson';
import { prisma } from "~/server/db";
import { appRouter } from "~/server/api/root";
import type { GetStaticProps,  NextPage } from "next";
import { BiDotsVertical } from "react-icons/bi";
dayjs.extend(relativeTime);



export const getStaticProps: GetStaticProps = async (context) => {
  const ssg = createServerSideHelpers({
    router: appRouter,
    ctx: { prisma, userId: null },
    transformer: superjson, // optional - adds superjson serialization
  });

  const slug = context.params?.slug;

  if (typeof slug !== "string") {
    throw new Error("No slug");
  }

  const username = slug.replace("@", "");

  await ssg.profile.getUserByUsername.prefetch({ username  });

  return {
    props: {
      trpcState: ssg.dehydrate(),
      username,
    },
  }
};

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  }
}


const ProfilePage: NextPage<{username: string}> = ({ username }) => {

  const { data} = api.profile.getUserByUsername.useQuery({
    username: "chayesss"
  }); 

  // return empty div if data not loaded
  if (!data) return <div>404</div>;



  return (
    <>
      <Head>
        <title>{`@${data.username || ""} / KBDSpace`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <div>
          <MobileHeader />
        </div>
        <div className="flex flex-col sm:flex-row justify-center h-full gap-4 m-4 pt-16 lg:pt-0">
          <div className="hidden lg:block flex-shrink-0 w-[22rem] mr-4 h-screen overflow-y-auto">
            <SideBar />
          </div>
          <div className="w-full max-w-6xl ">
            <div>
              
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default ProfilePage;
