import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";
import { SideBar } from "~/components/sidebar";

import { LoadingSpinner } from "~/components/loading";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import { useState } from "react";
import { MyButton } from "~/components/custombutton";
dayjs.extend(relativeTime);



// create post form with title, content, and submit button
const CreatePostForm = () => {

    const ctx = api.useContext();

    //TODO: REDIRECT TO HOME PAGE AFTER POSTING
    const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
        onSuccess: () => {

            setTitle("");
            setContent("");

            void ctx.posts.getAll.invalidate();

        }
    });

    const [title, setTitle] = useState("");
    const [content, setContent] = useState("");
    const [tag, setTag] = useState("News");

    return (
        <div className="p-8 bg-gradient-to-t from-gray-950 to-gray-900 border border-slate-800 shadow shadow-black rounded-lg flex flex-col gap-4 w-full h-full">
            <h1 className="text-3xl font-bold">Create Post</h1>
            <p>All fields marked with * are required</p>
            <label className="text-2xl  font-semibold" htmlFor="title">Title*</label>
            <input
                className="border-2 border-slate-800 bg-transparent rounded-md w-1/2 focus:outline-none focus:ring-0 focus:border-slate-400 focus:bg-gray-950 peer"
                type="text"
                placeholder=" Title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                required
                disabled={isPosting}
            />
            <label className="text-2xl font-semibold" htmlFor="tag">Tag*</label>
            <select
                className="block py-2.5 w-1/6 px-1 text-sm bg-transparent border-2 rounded-md border-slate-800 focus:outline-none focus:ring-0 focus:border-slate-400 focus:bg-gray-950 peer"
                name="tag"
                placeholder="tag"
                value={tag}
                required
                onChange={(e) => setTag(e.target.value)} >
                <option value="News">News</option>
                <option value="Meme">Meme</option>
                <option value="Discussion">Discussion</option>
                <option value="Question">Question</option>
                <option value="Announcement">Announcement</option>
            </select>
            <label className="text-2xl font-semibold" htmlFor="content">Content*</label>
            <textarea
                className="border-2 border-slate-800 bg-transparent rounded-md h-32 focus:outline-none focus:ring-0 focus:border-slate-400 focus:bg-gray-950 peer"
                placeholder=" Content"
                value={content}
                onChange={(e) => setContent(e.target.value)}
                required
                disabled={isPosting}
            />
            <MyButton name="Post" onClick={() => mutate({ title: title, content: content, tag: tag })}></MyButton>
        </div>
    )
};



export default function Home() {

    const {isLoaded: userLoaded, } = useUser();



    // return empty div if user not loaded
    if (!userLoaded) return <LoadingSpinner />;



    return (
        <>
            <Head>
                <title>kbdspace</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className="flex flex-col sm:flex-row justify-center h-screen  gap-4 m-2">
                <div className="flex-shrink-0 w-[22rem] mr-4 h-screen">
                    <SideBar />
                </div>
                <div className="w-full md: max-w-5xl ">
                    <div className="flex flex-row p-4">
                        <CreatePostForm />
                    </div>
                </div>
            </main>
        </>
    );
}
