import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {

  const user = useUser()

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>kbdspace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1>kbdspace</h1>
        <div>
          {!user.isSignedIn && <SignInButton />}{!!user.isLoaded && <SignOutButton />}
        </div>
        <div>
          {data?.map((post) => (
          <div key={post.id}>{post.title}</div>)) ?? <div>Loading...</div>}
        </div>
        
      </main>
    </>
  );
}
