import { SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const NewPostButton = () => () => {
  const { user } = useUser();

  if (!user) return null;

  return <div>
    <img src={user.profileImageUrl} alt='pfp' />
  </div>

}

export default function Home() {

  const user = useUser()

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return (<div>Loading...</div>);

  if (!data) return (<div>Something went wrong...</div>);

  return (
    <>
      <Head>
        <title>kbdspace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="flex justify-center h-screen">
        <div className="w-full md: max-w-5xl border-x">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <UserButton
              userProfileMode="navigation"
              userProfileUrl={
                typeof window !== "undefined"
                  ? `${window.location.origin}/profile`
                  : undefined
              }
            />}
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (
              <div key={post.id} className="p-8 border-b">{post.title}</div>)) ?? <div>Loading...</div>}
          </div>
        </div>
      </main>
    </>
  );
}
