import Head from "next/head";
import { api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import { SideBar } from "~/components/sidebar";
import { MobileHeader } from "~/components/mobileheader";
import type { GetStaticProps,  NextPage } from "next";
import PostView from "~/components/postview";
import { generateSSGHelper } from "~/server/helpers/ssgHelper";
import { IoIosArrowRoundBack } from "react-icons/io";
import Link from "next/link";
dayjs.extend(relativeTime);



export const getStaticProps: GetStaticProps = async (context) => {
  
  const ssg = generateSSGHelper();
  const id = context.params?.id;

  if (typeof id !== "string") {
    throw new Error("No id");
  }


  await ssg.posts.getById.prefetch({ id  });

  return {
    props: {
      trpcState: ssg.dehydrate(),
      id,
    },
  }
};

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  }
}




const PostPage: NextPage<{id : string}> = ({ id }) => {

  const { data } = api.posts.getById.useQuery({ id }); 

  // return empty div if data not loaded
  if (!data) return <div>404</div>;



  return (
    <>
      <Head>
        <title>{`${data.post.title} - @${data.author.username || ""} / KBDSpace`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <MobileHeader />
        </div>
        <div className="flex flex-col sm:flex-row justify-center h-full gap-4 m-4 pt-16 lg:pt-0">
          <div className="hidden lg:block flex-shrink-0 w-[22rem] mr-4 h-screen overflow-y-auto">
            <SideBar />
          </div>
          <div className="w-full max-w-6xl ">
            <div className="flex flex-row gap-4 pb-6">
              <div className="mr-2 flex flex-row hover:underline items-center">
                  <Link href="/" className="w-[8rem] text-slate-100 flex flex-row items-center text-lg gap-2">
                    <IoIosArrowRoundBack size={24} /><p>Go back</p>
                  </Link>
              </div>
            </div>
            <div className="">
              <PostView {...data} isFullPost={true}/>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default PostPage;
